/*
This is the root of the project. 
The command to run the project is: pnpm run dev 
Ensure that you have the most recent version of the project by runnning "git fetch" then "git merge origin/main"
IMPORTANT: PLEASE ENSURE THE PORT YOU ARE RUNNING THIS ON IS 3000 DUE TO GOOGLE AUTH CONFIGURATION
*/
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
